'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowDown,ArrowUpRight,Leaf,RotateCcw } from 'lucide-react';
import Forest from './forest';
const acts=[{label:'THE BEGINNING',title:<>Every forest<br/>begins with <em>one.</em></>,copy:'A seed. A little light. A world waiting to unfold.'},{label:'BECOMING',title:<>Give it time.<br/><em>Watch it grow.</em></>,copy:'Follow the branches. Rise with the leaves.'},{label:'INTO THE WILD',title:<>You are part<br/>of <em>something bigger.</em></>,copy:'Keep going. There is a whole world beneath the canopy.'},{label:'A NEW SEASON',title:<>Nothing ends.<br/>It simply <em>changes.</em></>,copy:'Leaves fall. Light shifts. Life begins again.'}];
export default function Home(){const progress=useRef(0);const [p,setP]=useState(0);const [ready,setReady]=useState(false);const [error,setError]=useState(false);const frame=useRef(0);
 useEffect(()=>{const update=()=>{frame.current=0;const value=Math.max(0,Math.min(1,scrollY/(document.documentElement.scrollHeight-innerHeight)));progress.current=value;setP(value)};const scroll=()=>{if(!frame.current)frame.current=requestAnimationFrame(update)};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);update();return()=>{cancelAnimationFrame(frame.current);removeEventListener('scroll',scroll);removeEventListener('resize',scroll)}},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'set_forest_journey',description:'Move to a chapter of the 3D forest journey and report rendering status.',inputSchema:{type:'object',properties:{progress:{type:'number',minimum:0,maximum:1}},required:['progress'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(typeof input?.progress!=='number'||!Number.isFinite(input.progress)||input.progress<0||input.progress>1)throw new Error('Progress must be from 0 to 1.');window.scrollTo({top:input.progress*(document.documentElement.scrollHeight-innerHeight),behavior:'instant'});await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {progress:progress.current,ready,error};}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[ready,error]);
 const jump=(n:number)=>window.scrollTo({top:n*(document.documentElement.scrollHeight-innerHeight),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});const act=p<.23?0:p<.51?1:p<.78?2:3;
 return <main className="experience"><div className="fixed-scene"><Forest progress={progress} onReady={()=>setReady(true)} onError={()=>setError(true)}/>{(!ready||error)&&<div className="fallback"><img src="/images/fern.jpg" alt="Forest fern foliage"/><p>{error?'The 3D forest could not load. Try refreshing in a WebGL-enabled browser.':'Growing your little world…'}</p></div>}<div className="vignette"/></div>
 <header className="topbar"><a className="brand" href="#"><Leaf size={22} strokeWidth={1.4}/> VERDANT<span>®</span></a><span className="edition">AN IMMERSIVE NATURE STUDY — 001</span><button onClick={()=>jump(.55)}>Enter the forest <ArrowUpRight size={16}/></button></header>
 <aside className="side-index" aria-label="Scene chapters">{acts.map((a,i)=><button key={a.label} onClick={()=>jump([0,.3,.59,.88][i])} aria-label={a.label} aria-current={act===i?'step':undefined}><span className={act===i?'selected':''}/>0{i+1}</button>)}</aside>
 <div className="story-copy">{acts.map((a,i)=><section key={i} className={'act '+(act===i?'active':'')} aria-hidden={act!==i}><p className="eyebrow"><span className="live-dot"/>0{i+1} / {a.label}</p><h1>{a.title}</h1><p className="description">{a.copy}</p>{i===0?<button tabIndex={act===i?0:-1} className="journey-link" onClick={()=>jump(.3)}><span><ArrowDown size={18}/></span>Scroll to bring it to life</button>:i===3?<button tabIndex={act===i?0:-1} className="journey-link" onClick={()=>jump(0)}><span><RotateCcw size={18}/></span>Begin again</button>:null}</section>)}</div>
 <div className="coordinates"><span>THE LIVING WORLD</span><b>{act===0?'ROOTED IN POSSIBILITY':act===1?'REACHING FOR THE LIGHT':act===2?'BENEATH THE CANOPY':'RETURNING TO THE EARTH'}</b></div>
 <footer className="bottom-bar"><span>SCROLL SLOWLY <ArrowDown size={12}/></span><div className="progress-track"><i style={{width:String(p*100)+'%'}}/></div><span>{String(Math.round(p*100)).padStart(2,'0')} / 100</span><a href="https://github.com/dgreenheck/ez-tree" target="_blank" rel="noreferrer" className="credits">TREE STUDY ↗</a></footer>
 <div className="scroll-space" aria-hidden="true"/>
 </main>
}
