'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, Plus, Minus, Flame, X, Pause, Play, RotateCcw, Volume2, VolumeX } from 'lucide-react';
import BurgerScene from './scene';
import {useFoodSound} from './sound';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const dishes=[
 {id:'burger',name:'The Ember Double',tag:'THE SIGNATURE',price:349,image:'burger.jpg',description:'Two flame-grilled patties, melted cheddar, crisp greens, tomato and our smoky house sauce. All tucked into a toasted sesame bun.',allergens:'Contains wheat, milk, egg and sesame.'},
 {id:'fries',name:'Golden Hour Fries',tag:'THE PERFECT SIDE',price:149,image:'fries.jpg',description:'Golden, crisp potato fries with a generous pinch of sea salt. Made for dipping, sharing, and stealing the last one.',allergens:'Prepared in a shared kitchen.'},
 {id:'drink',name:'The Ice-Cold Cola',tag:'THE COOL DOWN',price:129,image:'drink.jpg',description:'Sparkling cola, poured over plenty of ice. The refreshing little reset between big bites.',allergens:'Ask about ingredient substitutions.'},
];
const money=(n:number)=>`₹${n}`;
export default function Home(){
 const stage=useRef<HTMLElement>(null),progress=useRef(0),[p,setP]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState(false),[paused,setPaused]=useState(false),pausedRef=useRef(false);
 const [selected,setSelected]=useState<typeof dishes[number]|null>(null),[bag,setBag]=useState<Record<string,number>>({}),[bagOpen,setBagOpen]=useState(false),[spice,setSpice]=useState('Smoky'),[message,setMessage]=useState('');
 const sound=useFoodSound(progress);
 const stateRef=useRef({ready,error,bag});stateRef.current={ready,error,bag};
 const total=dishes.reduce((n,d)=>n+(bag[d.id]||0)*d.price,0),count=Object.values(bag).reduce((a,b)=>a+b,0);
 function add(id:string){sound.click();setBag(b=>({...b,[id]:(b[id]||0)+1}));setMessage('Added to your tasting tray');}
 function jump(value:number){if(stage.current)window.scrollTo({top:stage.current.offsetTop+value*(stage.current.offsetHeight-innerHeight),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 useEffect(()=>{pausedRef.current=paused},[paused]);
 useEffect(()=>{let raf=0;const update=()=>{if(stage.current){const val=Math.max(0,Math.min(1,-stage.current.getBoundingClientRect().top/(stage.current.offsetHeight-innerHeight)));progress.current=val;setP(val);}raf=0};const onScroll=()=>{if(!raf)raf=requestAnimationFrame(update)};window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);update();return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onScroll);cancelAnimationFrame(raf)}},[]);
 useEffect(()=>{if(message){const id=setTimeout(()=>setMessage(''),2500);return()=>clearTimeout(id)}},[message]);
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tools=[{
   name:'set_burger_journey',description:'Navigate the 3D burger story to a progress value from zero to one. Returns renderer readiness.',inputSchema:{type:'object',properties:{progress:{type:'number',minimum:0,maximum:1}},required:['progress'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},
   async execute(input:unknown){const x=input as {progress?:number};if(!x||typeof x.progress!=='number'||!Number.isFinite(x.progress)||x.progress<0||x.progress>1)throw new Error('Progress must be a number from 0 to 1');setBagOpen(false);if(stage.current)window.scrollTo({top:stage.current.offsetTop+x.progress*(stage.current.offsetHeight-innerHeight),behavior:'instant'});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {progress:progress.current,ready:stateRef.current.ready,error:stateRef.current.error};}
  },{
   name:'set_tasting_tray',description:'Configure the demo tasting tray by setting quantities for the burger, fries, and drink. No order or payment is placed.',inputSchema:{type:'object',properties:{burger:{type:'integer',minimum:0,maximum:20},fries:{type:'integer',minimum:0,maximum:20},drink:{type:'integer',minimum:0,maximum:20}},required:['burger','fries','drink'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},
   async execute(input:unknown){const x=input as Record<string,number>;if(!x||typeof x!=='object'||Object.keys(x).length!==3||!['burger','fries','drink'].every(k=>Number.isInteger(x[k])&&x[k]>=0&&x[k]<=20))throw new Error('Provide burger, fries and drink quantities from 0 to 20');setBag({burger:x.burger,fries:x.fries,drink:x.drink});setBagOpen(true);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {quantities:stateRef.current.bag,total:dishes.reduce((n,d)=>n+d.price*(stateRef.current.bag[d.id]||0),0),currency:'INR',demo:true};}
  }];
  for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn)}catch(e){console.warn(e)}}return()=>lifecycle.abort();
 },[]);
 return <main>
  <header className="nav"><a href="#" className="wordmark" aria-label="Ember home">EMBER<span>®</span></a><nav aria-label="Main navigation"><button onClick={()=>jump(.5)}>THE GOOD STUFF</button><a href="#menu">OUR MENU</a><a href="#philosophy">OUR FIRE</a></nav><button className="tray-button" onClick={()=>setBagOpen(true)}>TASTING TRAY <span>{count.toString().padStart(2,'0')}</span><ArrowUpRight size={17}/></button></header>
  <section ref={stage} className="journey" aria-label="An interactive journey through the signature burger"><div className={`theatre ${p>.25&&p<.76?'is-orange':''}`}>
   <div className="ghost-type" aria-hidden="true" style={{transform:`translateX(${-p*12}%)`}}>CRAVE IT.</div>
   <BurgerScene progress={progress} paused={pausedRef} onReady={()=>setReady(true)} onError={()=>setError(true)}/>
   {(!ready||error)&&<div className="scene-fallback"><img src="/images/burger.jpg" alt="A juicy cheeseburger with a golden sesame bun"/>{!error&&<span>Warming up the grill…</span>}</div>}
   <div className={`scene-copy intro ${p<.23?'visible':''}`} aria-hidden={p>=.23}><span className="eyebrow"><i/> SERIOUS FLAVOUR. ZERO RESTRAINT.</span><h1>LOVE AT<br/>FIRST <em>BITE.</em></h1><p>Flame-kissed. Stacked high. Made to make you forget your table manners.</p><a className="pill dark" href="#menu" tabIndex={p<.23?0:-1}>MEET YOUR NEXT CRAVING <ArrowUpRight size={19}/></a><div className="hero-detail"><span>THE EMBER DOUBLE</span><b>Two patties. One obsession.</b></div></div>
   <div className={`scene-copy anatomy ${p>=.23&&p<.76?'visible':''}`} aria-hidden={p<.23||p>=.76}><span className="eyebrow">01 / NOTHING TO HIDE</span><h2>EVERY<br/>LAYER.<br/><em>LOUDER.</em></h2><p>Soft bun. Sharp cheddar.<br/>Smoky char. That fresh crunch.<br/>A little chaos. A perfect bite.</p></div>
   <div className={`ingredient-notes ${p>=.30&&p<.71?'visible':''}`} aria-hidden="true"><span>01 — TOASTED SESAME</span><span>02 — FRESH & CRUNCHY</span><span>03 — FLAME-GRILLED</span><span>04 — MELTED CHEDDAR</span><span>05 — THE FOUNDATION</span></div>
   <div className={`scene-copy finish ${p>=.76?'visible':''}`} aria-hidden={p<.76}><span className="eyebrow">03 / THE FULL EXPERIENCE</span><h2>MAKE IT<br/><em>A MEAL.</em></h2><p>A big stack. Golden fries. Ice-cold cola.<br/>The whole delicious picture.</p><a href="#menu" className="pill dark" tabIndex={p>=.76?0:-1}>TAKE A BITE <ArrowDown size={18}/></a></div>
   <div className="scene-bottom"><button className="scroll-hint" onClick={()=>p>.96?document.getElementById('menu')?.scrollIntoView({behavior:'smooth'}):jump(Math.min(1,p+.38))}><ArrowDown size={17}/> SCROLL TO UNSTACK THE GOOD STUFF</button><div className="progress"><span style={{width:`${p*100}%`}}/></div><button className="sound-toggle" onClick={sound.toggle} aria-pressed={sound.enabled} aria-label={sound.enabled?'Mute sound effects':'Enable sound effects'}>{sound.enabled?<Volume2 size={15}/>:<VolumeX size={15}/>}<span>SOUND {sound.enabled?'ON':'OFF'}</span></button><button className="motion-toggle" onClick={()=>setPaused(v=>!v)} aria-label={paused?'Resume ambient animation':'Pause ambient animation'}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><span className="scene-index">{p<.23?'01':p<.76?'02':'03'} / 03</span></div>
  </div></section>
  <div className="ticker" aria-hidden="true"><span>GOOD FOOD. GOOD MOOD. <Flame/> FIRE UP YOUR APPETITE. <Flame/> GOOD FOOD. GOOD MOOD. <Flame/> FIRE UP YOUR APPETITE. <Flame/></span></div>
  <section id="menu" className="menu-section"><div className="section-heading"><div><span className="eyebrow">THE SHORTLIST / ALL THE RIGHT CHOICES</span><h2>FOLLOW YOUR<br/><em>APPETITE.</em></h2></div><p>One legendary stack.<br/>A couple of very good accomplices.</p></div><div className="menu-grid">{dishes.map((d,i)=><article className="dish" key={d.id}><button className="dish-image" onClick={()=>setSelected(d)} aria-label={`Explore ${d.name}`}><img src={`/images/${d.image}`} alt={d.name} loading="lazy"/><span className="dish-tag">{d.tag}</span><span className="image-explore"><ArrowUpRight/></span></button><div className="dish-line"><span className="dish-number">0{i+1}</span><h3><button onClick={()=>setSelected(d)}>{d.name}</button></h3><span>{money(d.price)}</span></div><p>{d.description.split('. ')[0]}.</p><button className="add-button" onClick={()=>add(d.id)}>ADD TO TASTING TRAY <Plus size={18}/></button></article>)}</div><p className="demo-note">A concept menu. Prices and photos are illustrative; the tasting tray is a demo, and no orders or payments are taken.</p></section>
  <section className="fire-section" id="philosophy"><div className="fire-title"><span className="eyebrow">A LITTLE FIRE GOES A LONG WAY.</span><h2>LESS FUSS.<br/>MORE <em>FLAVOUR.</em></h2><p>EMBER is a love letter to the simple things done properly: a hot grill, a golden bun, and food that brings everyone to the table.</p><a href="#menu" className="pill light">FIND YOUR FAVOURITE <ArrowUpRight size={18}/></a></div><div className="flavour-panel"><Flame size={35}/><span className="eyebrow">WHAT'S YOUR KIND OF FIRE?</span><h3>{spice==='Smoky'?'LOW & SLOW.':spice==='Spicy'?'TURN IT UP.':'KEEP IT CLASSIC.'}</h3><p>{spice==='Smoky'?'Rich, rounded, and full of that just-off-the-grill character.':spice==='Spicy'?'A punchy chilli kick for the bite that bites back.':'Golden, cheesy comfort. Some classics need no introduction.'}</p><div className="flavour-options" aria-label="Flavour preference">{['Classic','Smoky','Spicy'].map(s=><button key={s} onClick={()=>setSpice(s)} aria-pressed={s===spice}>{s}</button>)}</div></div></section>
  <footer><div className="footer-top"><p>COME HUNGRY.<br/>LEAVE HAPPY.</p><button onClick={()=>jump(0)}>ANOTHER LOOK? <RotateCcw size={17}/></button></div><div className="footer-brand">EMBER®</div><div className="footer-bottom"><span>© 2026 EMBER — RESTAURANT CONCEPT BY ASTRA</span><a href="/credits.html">ASSET CREDITS</a><span>MADE WITH A LITTLE EXTRA FIRE.</span></div></footer>
  <div className="toast" role="status">{message}</div>
  <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="food-modal">{selected&&<><img src={`/images/${selected.image}`} alt={selected.name}/><span className="eyebrow">{selected.tag}</span><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.description}</DialogDescription><p className="allergens">{selected.allergens}</p><button className="pill dark" onClick={()=>{add(selected.id);setSelected(null)}}>ADD TO TRAY · {money(selected.price)} <Plus size={18}/></button></>}</DialogContent></Dialog>
  <Dialog open={bagOpen} onOpenChange={setBagOpen}><DialogContent className="tray-modal"><DialogTitle>Your tasting tray</DialogTitle><DialogDescription>Build your perfect combination. This is a demo; no order will be placed.</DialogDescription>{count===0?<p className="empty-tray">A little empty. A lot of potential.<br/><button className="pill dark" onClick={()=>{setBagOpen(false);document.getElementById('menu')?.scrollIntoView({behavior:'smooth'})}}>EXPLORE THE MENU <ArrowDown size={18}/></button></p>:<>{dishes.filter(d=>bag[d.id]).map(d=><div className="tray-row" key={d.id}><img src={`/images/${d.image}`} alt=""/><div><b>{d.name}</b><span>{money(d.price*bag[d.id])}</span></div><button aria-label={`Remove one ${d.name}`} onClick={()=>setBag(b=>({...b,[d.id]:Math.max(0,b[d.id]-1)}))}><Minus size={16}/></button><span>{bag[d.id]}</span><button aria-label={`Add one ${d.name}`} onClick={()=>add(d.id)}><Plus size={16}/></button></div>)}<div className="tray-total"><span>YOUR DEMO TOTAL</span><b>{money(total)}</b></div><button className="pill dark" onClick={()=>{setBag({});setMessage('Fresh tray. Fresh possibilities.')}}>CLEAR TRAY <X size={18}/></button></>}</DialogContent></Dialog>
 </main>
}
