'use client';
import {useCallback,useEffect,useRef,useState,type MutableRefObject} from 'react';
/** Small, locally synthesized food foley. No recordings, tracking, or autoplay. */
export function useFoodSound(progress:MutableRefObject<number>){
 const [enabled,setEnabled]=useState(false),context=useRef<AudioContext|null>(null),master=useRef<GainNode|null>(null),noise=useRef<AudioBuffer|null>(null),last=useRef(0),lastPlayed=useRef(0);
 const tone=useCallback((frequency:number,duration:number,level=.08,delay=0)=>{const c=context.current,m=master.current;if(!c||!m)return;const o=c.createOscillator(),g=c.createGain(),now=c.currentTime+delay;o.type='sine';o.frequency.setValueAtTime(frequency,now);o.frequency.exponentialRampToValueAtTime(frequency*.82,now+duration);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(level,now+.006);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(m);o.start(now);o.stop(now+duration+.02);},[]);
 const breath=useCallback((duration:number,frequency:number,level:number,end:number)=>{const c=context.current,m=master.current,b=noise.current;if(!c||!m||!b)return;const src=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain(),now=c.currentTime;src.buffer=b;filter.type='bandpass';filter.Q.value=.7;filter.frequency.setValueAtTime(frequency,now);filter.frequency.exponentialRampToValueAtTime(end,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(level,now+Math.min(.06,duration*.3));gain.gain.exponentialRampToValueAtTime(.0001,now+duration);src.connect(filter);filter.connect(gain);gain.connect(m);src.start(now);src.stop(now+duration+.02);},[]);
 const play=useCallback((kind:'whoosh'|'stack'|'crunch'|'fizz'|'tap')=>{if(!context.current||context.current.state!=='running')return;if(kind==='whoosh')breath(.34,350,.22,2200);if(kind==='stack'){tone(130,.18,.25);breath(.12,550,.10,240);}if(kind==='crunch'){breath(.22,2400,.19,850);tone(620,.035,.035,.06);}if(kind==='fizz'){breath(.72,3800,.12,5800);tone(1900,.3,.075,.04);tone(2760,.25,.035,.15);}if(kind==='tap'){tone(650,.065,.12);tone(920,.09,.055,.04);}},[breath,tone]);
 const toggle=useCallback(async()=>{if(enabled){setEnabled(false);if(master.current&&context.current){master.current.gain.setTargetAtTime(0,context.current.currentTime,.02);}return;}try{if(!context.current){const c=new AudioContext();context.current=c;const g=c.createGain();g.gain.value=.34;g.connect(c.destination);master.current=g;const b=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=b.getChannelData(0);let seed=173;for(let i=0;i<data.length;i++){seed=(seed*16807)%2147483647;data[i]=(seed/2147483647)*2-1;}noise.current=b;}await context.current.resume();master.current!.gain.setTargetAtTime(.34,context.current.currentTime,.025);last.current=progress.current;setEnabled(true);play('tap');}catch{setEnabled(false);}},[enabled,play,progress]);
 useEffect(()=>{if(!enabled)return;let id=0;last.current=progress.current;const frame=()=>{id=requestAnimationFrame(frame);const p=progress.current,prev=last.current;last.current=p;if(document.hidden||!context.current)return;const now=context.current.currentTime;const triggers:[number,'whoosh'|'stack'|'crunch'|'fizz'][]=[[.23,'whoosh'],[.61,'whoosh'],[.80,'stack'],[.89,'crunch'],[.96,'fizz']];for(const [at,effect]of triggers){if((prev<at&&p>=at)||(prev>at&&p<=at)){if(now-lastPlayed.current>.25){play(p>=prev?effect:'whoosh');lastPlayed.current=now;}break;}}};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id)},[enabled,play,progress]);
 useEffect(()=>()=>{void context.current?.close();context.current=null;},[]);
 return {enabled,toggle,click:()=>{if(enabled)play('tap')}};
}
