'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUpRight,ArrowLeft,ArrowRight,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import Scene from './scene';
import {projects} from './projects';
export default function Home(){
 const progress=useRef(0);const [p,setP]=useState(0);const [ready,setReady]=useState(false);const [failed,setFailed]=useState(false);const [selected,setSelected]=useState<number|null>(null);
 const active=Math.max(0,Math.min(5,Math.round((p-.23)/.108)));const inGallery=p>.18&&p<.92;
 const jump=(value:number)=>window.scrollTo({top:value*(document.documentElement.scrollHeight-innerHeight),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 useEffect(()=>{let frame=0;const update=()=>{frame=0;const n=scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight);progress.current=n;setP(n)};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);update();return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',scroll);removeEventListener('resize',scroll)}},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'explore_prism_world',description:'Navigate to a PRISM gallery world and optionally open its project preview.',inputSchema:{type:'object',properties:{world:{type:'integer',minimum:1,maximum:6},openPreview:{type:'boolean'}},required:['world'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!Number.isInteger(input?.world)||input.world<1||input.world>6||input.openPreview!==undefined&&typeof input.openPreview!=='boolean')throw new Error('Choose a world from 1 to 6.');const index=input.world-1;window.scrollTo({top:(.23+index*.108)*(document.documentElement.scrollHeight-innerHeight),behavior:'instant'});setSelected(input.openPreview?index:null);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return{world:input.world,title:projects[index].title,previewOpen:!!input.openPreview,sceneReady:ready,fallback:failed};}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[ready,failed]);
 return <main><div className="scene"><Scene progress={progress} onReady={()=>setReady(true)} onError={()=>{setFailed(true);setReady(true)}}/></div><div className="edge-shade"/>
 <header><a className="wordmark" href="#">PRISM<span>®</span></a><nav aria-label="Main navigation"><button onClick={()=>jump(.23)}>Selected worlds <span>06</span></button><button onClick={()=>jump(.96)}>The idea</button></nav><button className="outline" onClick={()=>jump(.23)}>Enter the gallery <ArrowUpRight size={15}/></button></header>
 {!ready&&<div className="loader" role="status"><span className="loading-ring"/><p>SETTING THE SCENE</p><span>A different dimension is coming into focus.</span></div>}
 <section className="hero" style={{opacity:Math.max(0,1-p*7),visibility:p>.18?'hidden':'visible'}}><div className="hero-kicker"><span className="status-dot"/>INDEPENDENT WORLDS. INFINITE POSSIBILITIES.</div><h1>PRISM</h1><div className="hero-bottom"><p>Ideas are meant<br/>to be <em>experienced.</em></p><p className="intro">A collection of digital worlds.<br/>Made to move you somewhere new.</p><button className="round" aria-label="Scroll into the gallery" onClick={()=>jump(.23)}><ArrowDown/></button></div></section>
 {inGallery&&<><div className="gallery-label"><span>SELECTED WORLDS</span><b>0{active+1} — 06</b></div><div className="work-copy" key={active}><p className="kicker">{projects[active].category}</p><h2>{projects[active].title}</h2><button onClick={()=>setSelected(active)}>Step inside this world <Plus size={18}/></button></div><div className="gallery-controls"><button className="round" onClick={()=>jump(.23+Math.max(0,active-1)*.108)} disabled={active===0} aria-label="Previous world"><ArrowLeft size={19}/></button><button className="round" onClick={()=>jump(.23+Math.min(5,active+1)*.108)} disabled={active===5} aria-label="Next world"><ArrowRight size={19}/></button></div></>}
 {failed&&<div className="flat-gallery"><img src={'/images/'+projects[active].image+'.jpg'} alt={projects[active].title}/></div>}
 <section className={'outro '+(p>.92?'visible':'')} aria-hidden={p<=.92}><p className="kicker">A DIFFERENT PERSPECTIVE</p><h2>Less ordinary.<br/><em>More possibility.</em></h2><p>Six worlds. One idea: the web should be a place<br className="desktop-break"/> you experience, not just a page you pass through.</p><button className="outline" tabIndex={p>.92?0:-1} onClick={()=>jump(0)}>Experience it again <ArrowUpRight size={16}/></button></section>
 <footer><span>SCROLL TO EXPLORE <ArrowDown size={12}/></span><div className="journey-meter"><i style={{width:`${p*100}%`}}/></div><span>{String(Math.round(p*100)).padStart(2,'0')} / 100</span><a href="/credits.html" target="_blank" rel="noreferrer">A STUDY BY ASTRA ↗</a></footer>
 <div className="scroll-track"/>
 <Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="project-modal">{selected!==null&&<><img className="modal-art" src={'/images/'+projects[selected].image+'.jpg'} alt={projects[selected].title}/><div className="modal-body"><p className="kicker">WORLD 0{selected+1} / {projects[selected].category}</p><DialogTitle>{projects[selected].title}</DialogTitle><DialogDescription>{projects[selected].description}</DialogDescription>{projects[selected].link?<a className="outline" href={projects[selected].link!} target="_blank" rel="noreferrer">{projects[selected].label}<ArrowUpRight size={17}/></a>:<p className="concept-note">An original visual concept in the PRISM collection.</p>}</div></>}</DialogContent></Dialog>
 </main>
}
