'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUpRight,MoveUpRight,RotateCcw} from 'lucide-react';
import Cosmos,{type RenderState} from './cosmos';
const chapters=[
 {name:'Departure',title:['There is more','out there.'],copy:'Leave the familiar behind. Follow a little curiosity into the dark.',place:'EARTH',detail:'Our point of departure',p:0},
 {name:'The blue hour',title:['Everything we know.','One blue world.'],copy:'A thin blue edge. An ocean of silence. Home, seen from a different side.',place:'LOW EARTH ORBIT',detail:'Look back before you go',p:.17},
 {name:'Lunar passage',title:['A quieter','kind of beautiful.'],copy:'Drift over ancient craters and a landscape written in light and shadow.',place:'THE MOON',detail:'Beyond the blue',p:.34},
 {name:'Between worlds',title:['Let wonder','pull you further.'],copy:'Through fragments of another time. Past the places without names.',place:'DEEP SPACE',detail:'In the space between',p:.50},
 {name:'The ringed world',title:['Some things','change your orbit.'],copy:'An impossible silhouette. A thousand delicate rings. A reason to keep going.',place:'SATURN',detail:'The great reveal',p:.69},
 {name:'Into the rings',title:['Small, in the','best possible way.'],copy:'Glide beneath the rings. Let the scale of it all sink in.',place:'THE RINGS',detail:'A different perspective',p:.85},
 {name:'Beyond',title:['The end is just','another beginning.'],copy:'There will always be another horizon. Stay curious.',place:'SOMEWHERE BEYOND',detail:'Until the next voyage',p:1},
];
export default function Home(){
 const progress=useRef(0),readyRef=useRef(false),renderState=useRef<RenderState>({ready:false,error:false,progress:0,objects:0,triangles:0}); const [p,setP]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState(false);const [stage,setStage]=useState('Finding our place in the universe');
 useEffect(()=>{document.getElementById('boot')?.remove(); const update=()=>{const n=Math.max(0,Math.min(1,scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)));progress.current=n;setP(n)};addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();return()=>{removeEventListener('scroll',update);removeEventListener('resize',update)}},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'navigate_space_journey',description:'Travel to a position in the visible space journey. Returns the active chapter and completed rendering status.',inputSchema:{type:'object',properties:{progress:{type:'number',minimum:0,maximum:1}},required:['progress'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{progress:number})=>{if(typeof input?.progress!=='number'||!Number.isFinite(input.progress)||input.progress<0||input.progress>1)throw new Error('Progress must be a number from 0 to 1.');scrollTo({top:input.progress*(document.documentElement.scrollHeight-innerHeight),behavior:'instant'});await new Promise<void>(resolve=>{const start=performance.now();const check=()=>{if((renderState.current.ready&&Math.abs(renderState.current.progress-input.progress)<.001)||performance.now()-start>5000)resolve();else requestAnimationFrame(check)};requestAnimationFrame(check)});const current=chapters.findLast(c=>progress.current>=c.p-.025)||chapters[0];return {chapter:current.name,requestedProgress:input.progress,scrollProgress:progress.current,scrollRange:document.documentElement.scrollHeight-innerHeight,...renderState.current};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const index=Math.min(chapters.length-1,chapters.findLastIndex(c=>p>=c.p-.025));const act=chapters[Math.max(0,index)];
 const jump=(n:number)=>window.scrollTo({top:n*(document.documentElement.scrollHeight-innerHeight),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 return <main className="experience">
 <div className="universe"><Cosmos state={renderState} progress={progress} onReady={()=>{readyRef.current=true;setReady(true)}} onStage={setStage} onError={()=>setError(true)}/><div className="scene-shade"/></div>
 <div className={'loader '+(ready&&!error?'done':'')} aria-hidden={ready&&!error}><span className="wordmark">EMBER<span>®</span></span><div className="loader-center"><span className="loader-orbit"/><p className="micro">PREPARING FOR DEPARTURE</p><h2>Wonder awaits.</h2><p role="status">{error?'We couldn’t open the 3D journey.':stage+'…'}</p>{error&&<button className="pill" onClick={()=>location.reload()}>Try again <ArrowUpRight size={17}/></button>}</div><span className="micro">A VOYAGE BY ASTRA</span></div>
 <div className={'interface '+(ready&&!error?'ready':'')} inert={!ready||error}>
 <header><a className="wordmark" href="#" onClick={e=>{e.preventDefault();jump(0)}}>EMBER<span>®</span></a><span className="header-caption">AN EXPLORATION OF THE EXTRAORDINARY</span><button className="pill" onClick={()=>jump(.69)}>Skip to Saturn <ArrowUpRight size={16}/></button></header>
 <div className="top-note"><span className="status-dot"/>A JOURNEY BEYOND EARTH <span>EST. 2026</span></div>
 <div className={'story '+(index===0?'opening':'')} key={index}><p className="chapter-label"><span>0{index+1}</span> {act.name}</p><h1>{act.title.map((line,i)=><span className="line" key={line}><span style={{animationDelay:i*100+'ms'}}>{i===1?<em>{line}</em>:line}</span></span>)}</h1><p className="story-copy">{act.copy}</p><button className="next-link" onClick={()=>jump(index===6?0:chapters[index+1].p)}><span>{index===6?<RotateCcw size={17}/>:<ArrowDown size={17}/>}</span>{index===0?'Scroll to depart':index===6?'Take the journey again':'Keep drifting'}</button></div>
 <div className="planet-caption"><span className="crosshair">＋</span><div><b>{act.place}</b><span>{act.detail}</span></div></div>
 <nav className="chapter-rail" aria-label="Journey chapters">{chapters.map((c,i)=><button key={c.name} className={index===i?'active':''} onClick={()=>jump(c.p)} aria-label={c.name} aria-current={index===i?'step':undefined}><i/><span>{String(i+1).padStart(2,'0')}</span></button>)}</nav>
 <footer><div className="footer-label"><span className="micro">SCROLL TO EXPLORE</span><ArrowDown size={15}/></div><div className="journey-progress"><span style={{transform:'scaleX('+p+')'}}/></div><span className="progress-number">{String(Math.round(p*100)).padStart(2,'0')}%</span><a href="/credits.html" target="_blank" rel="noreferrer">Texture credits <MoveUpRight size={12}/></a></footer>
 </div><div className="scroll-distance" aria-hidden="true"/>
 <noscript>This experience needs JavaScript to show its 3D space journey.</noscript>
 </main>
}
